# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OutWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OutWindow(object):
    def setupUi(self, OutWindow):
        OutWindow.setObjectName("OutWindow")
        OutWindow.resize(1366, 768)
        OutWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(OutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 500, 1360, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"font-colour:rgb(0, 85, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 0, 550, 550))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ok.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        OutWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OutWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        OutWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OutWindow)
        self.statusbar.setObjectName("statusbar")
        OutWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OutWindow)
        QtCore.QMetaObject.connectSlotsByName(OutWindow)

    def retranslateUi(self, OutWindow):
        _translate = QtCore.QCoreApplication.translate
        OutWindow.setWindowTitle(_translate("OutWindow", "MainWindow"))
        self.label.setText(_translate("OutWindow", "Validation Successful \n"
"Travel With Plesure."))
 

    def show_img_ok(self, OutWindow, msg, img):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("OutWindow",msg))
        #self.label_2.setPixmap(QtGui.QPixmap("ok.png"))
        self.label_2.setPixmap(QtGui.QPixmap(img))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OutWindow = QtWidgets.QMainWindow()
    ui = Ui_OutWindow()
    ui.setupUi(OutWindow)
    OutWindow.show()
    sys.exit(app.exec_())
