# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecoundWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecoundWindow(object):
    def setupUi(self, SecoundWindow):
        self.retryBtn1 = False
        SecoundWindow.setObjectName("SecoundWindow")
        SecoundWindow.resize(1366, 768)
        SecoundWindow.setMinimumSize(QtCore.QSize(1366, 768))
        SecoundWindow.setMaximumSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtWidgets.QWidget(SecoundWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setGeometry(QtCore.QRect(50, 100, 1271, 240))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter = QtWidgets.QSplitter(self.splitter_5)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setMinimumSize(QtCore.QSize(250, 60))
        self.label_3.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setEnabled(True)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_7 = QtWidgets.QLabel(self.splitter_2)
        self.label_7.setMinimumSize(QtCore.QSize(250, 60))
        self.label_7.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.splitter_2)
        self.label_8.setMinimumSize(QtCore.QSize(250, 60))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_12 = QtWidgets.QLabel(self.splitter_3)
        self.label_12.setMinimumSize(QtCore.QSize(250, 60))
        self.label_12.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.splitter_3)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_14 = QtWidgets.QLabel(self.splitter_4)
        self.label_14.setMinimumSize(QtCore.QSize(250, 60))
        self.label_14.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.splitter_4)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.splitter_6 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_6.setGeometry(QtCore.QRect(40, 360, 1281, 221))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.label_10 = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setVisible(False)

        SecoundWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecoundWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1360, 28))
        self.menubar.setObjectName("menubar")
        SecoundWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecoundWindow)
        self.statusbar.setObjectName("statusbar")
        SecoundWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecoundWindow)
        QtCore.QMetaObject.connectSlotsByName(SecoundWindow)
        self.pushButton_2.clicked.connect(self.retryBtn)

    def retranslateUi(self, SecoundWindow):
        _translate = QtCore.QCoreApplication.translate
        SecoundWindow.setWindowTitle(_translate("SecoundWindow", "SecoundWindow"))
        self.label_3.setText(_translate("SecoundWindow", "Passport Number "))
        self.label_4.setText(_translate("SecoundWindow", "fgdgd"))
        self.label_7.setText(_translate("SecoundWindow", "Name"))
        self.label_8.setText(_translate("SecoundWindow", "Arachhchillage psindu hajayaaj sijkama ajahauanmjajshankjjjs jjj jsjs "))
        self.label_12.setText(_translate("SecoundWindow", "Sex"))
        self.label_13.setText(_translate("SecoundWindow", "Arachhchillage psindu hajayaaj sijkama ajahauanmjajshankjjjs jjj jsjs "))
        self.label_14.setText(_translate("SecoundWindow", "Date Of Expiry"))
        self.label_15.setText(_translate("SecoundWindow", "Arachhchillage psindu hajayaaj sijkama ajahauanmjajshankjjjs jjj jsjs "))
        self.label_10.setText(_translate("SecoundWindow", "Scan Your Fingers One by One"))
        self.label_9.setText(_translate("SecoundWindow", "Finger info"))
        self.label_11.setText(_translate("SecoundWindow", "Instruction"))
        self.pushButton_2.setText(_translate("SecoundWindow", "Retry"))
 
    def setinfo(self, SecoundWindow, msg):
        _translate = QtCore.QCoreApplication.translate
        SecoundWindow.setWindowTitle(_translate("SecoundWindow", "SecoundWindow"))
        self.label_11.setText(_translate("SecoundWindow", msg))

    def setinfo1(self, SecoundWindow, msg):
        _translate = QtCore.QCoreApplication.translate
        SecoundWindow.setWindowTitle(_translate("SecoundWindow", "SecoundWindow"))
        self.label_9.setText(_translate("SecoundWindow", msg))
    
      
    def setinfoPassportNum(self, SecoundWindow, msg):
        _translate = QtCore.QCoreApplication.translate
        SecoundWindow.setWindowTitle(_translate("SecoundWindow", "SecoundWindow"))
        self.label_4.setText(_translate("SecoundWindow", msg))
        
    def setinfoName(self, SecoundWindow, msg):
        _translate = QtCore.QCoreApplication.translate
        SecoundWindow.setWindowTitle(_translate("SecoundWindow", "SecoundWindow"))
        self.label_8.setText(_translate("SecoundWindow", msg))
        
    def setinfoSex(self, SecoundWindow, msg):
        _translate = QtCore.QCoreApplication.translate
        SecoundWindow.setWindowTitle(_translate("SecoundWindow", "SecoundWindow"))
        self.label_13.setText(_translate("SecoundWindow", msg))
    
    def setinfoDoE(self, SecoundWindow, msg):
        _translate = QtCore.QCoreApplication.translate
        SecoundWindow.setWindowTitle(_translate("SecoundWindow", "SecoundWindow"))
        self.label_15.setText(_translate("SecoundWindow", msg))
    
        
        
    def initRetryBtn(self,SecoundWindow, msg):
        self.pushButton_2.setVisible(msg)
       # self.pushButton_2 = QtWidgets.QPushButton(self.splitter_6)
       # self.pushButton_2.setObjectName("pushButton_2")
       # self.pushButton_2.clicked.connect(self.retryBtn)
        #_translate = QtCore.QCoreApplication.translate
        #SecoundWindow.setWindowTitle(_translate("SecoundWindow", "SecoundWindow"))
        #self.pushButton_2.setText(_translate("SecoundWindow", "Retry"))
        
    def retryBtn(self,SecoundWindow):
        #self.pushButton_2.setVisible(False)
        self.retryBtn1 = True
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecoundWindow = QtWidgets.QMainWindow()
    ui = Ui_SecoundWindow()
    ui.setupUi(SecoundWindow)
    SecoundWindow.show()
    sys.exit(app.exec_())

